import React, { useState }  from "react";
import festivals from "../data/festivals.json";
import FestivalCard from "./FestivalCard";
import Style from "./FestivalList.module.css";
import jsPDF from "jspdf";

function FestivalList({ submittedSearch }) {
  const [selectedFestival, setSelectedFestival] = useState(null);
  const [selectedReligion, setSelectedReligion] = useState("All Religions");
  const [selectedMonth, setSelectedMonth] = useState("All Months");
 

  const religions = ["All Religions", ...new Set(festivals.map(f => f.religion))];
  const months = ["All Months", ...new Set(festivals.map(f => f.month))];

  const filteredFestivals = festivals.filter((festival) => {
  return (
    (selectedReligion === "All Religions" || festival.religion === selectedReligion) &&
    (selectedMonth === "All Months" || festival.month === selectedMonth) &&
    festival.name.toLowerCase().includes(submittedSearch.toLowerCase())
  );
});


const downloadPDF = (selectedFestival) => {
  const doc = new jsPDF();

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(selectedFestival.name, 10, 10);

  doc.setLineWidth(0.5);
  doc.line(10, 14, 200, 14);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);
  doc.text(`Country: ${selectedFestival.country}`, 10, 20);
  doc.text(`Religion: ${selectedFestival.religion}`, 10, 30);
  doc.text(`Month: ${selectedFestival.month}`, 10, 40);
 // doc.text(selectedFestival.description, 10, 50);

 const splitDescription = doc.splitTextToSize(
    selectedFestival.description,
    180
  );
  doc.text(splitDescription, 10, 60);

  doc.setFontSize(10);
  doc.text("Generated by Moonlight Events", 10, 280);

  doc.save(`${selectedFestival.name}.pdf`);
};


  return (
    <div id="festival-section" className="container bg-light" style={{  marginTop: '4rem'}}>
      <h2 className="text-center mb-4" style={{color: '#2b323cff', fontWeight: '700'}}>Popular <span style={{color: '#c60707'}}>Festivals</span> 🎉</h2>


      <div className="d-flex gap-3 mb-4 justify-content-center">

        {/* This is the Religion Filter */}
        <select className="form-select w-auto" value={selectedReligion} onChange={(e) => setSelectedReligion(e.target.value)}>
          {religions.map((religion) => (
          <option key={religion} value={religion}>{religion}</option>
        ))}
        </select>

        {/* This is the Month Filter */}
        <select className="form-select w-auto" value={selectedMonth} onChange={(e) => setSelectedMonth(e.target.value)}>
          {months.map((month) => (
          <option key={month} value={month}>{month}</option>
        ))}

          {/* 
          <option value="All">All Months</option>
          <option value="November">November</option>
          <option value="December">December</option>
          <option value="Varies">Varies</option> */}
        </select>


        {/* This is the search bar */}

        {/* <input type="text" className="form-control w-25" placeholder="Search festival..." value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)}/> */}

      </div>

      {submittedSearch && (
      <p className="text-center text-muted mt-5 mb-3" style={{ fontSize: "18px" }}>
        Showing results for "{submittedSearch}"
      </p>
  )}
  

      {/* This is the  Card section */}

      <div className="row mt-5">
        {filteredFestivals.length > 0 ? (
          filteredFestivals.map((festival) => (
            <FestivalCard key={festival.id} festival={festival}  onClick={() => setSelectedFestival(festival)} /> 
          ))
        ) : (
          <p className="text-center mt-4">No festivals found 😔</p>
        )}
      </div>

      {/* This is the  Modal for selected festival */}

      {selectedFestival && (
        <div className={`modal fade show d-block ${Style.modal}`}  onClick={() => setSelectedFestival(null)}>
          <div className="modal-dialog">
            <div className="modal-content">

              <div className="modal-header">
                <h5 className="modal-title">{selectedFestival.name}</h5>
                <button
                  className="btn-close"
                  onClick={() => setSelectedFestival(null)}
                ></button>
              </div>

              <div className="modal-body">
                <img
                  src={selectedFestival.image}
                  alt={selectedFestival.name}
                  className="img-fluid mb-3"
                  style={{maxHeight: "300px", width: "100%", objectFit: "cover", borderRadius: "4px"}}
                />
                <p><strong>Country:</strong> {selectedFestival.country}</p>
                <p><strong>Religion:</strong> {selectedFestival.religion}</p>
                <p><strong>Month:</strong> {selectedFestival.month}</p>
                <p>{selectedFestival.description}</p>
                <button className="btn w-100 mt-auto" style={{backgroundColor: "#c60707", color: "#fff"}} onClick={() => downloadPDF(selectedFestival)}>Download Details</button>
              </div>

            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default FestivalList;




/*

 #ffc107 

Is <FestivalCard ... /> like calling a function multiple times?

✔ YES — this is a very good way to think about it.

This line:

<FestivalCard key={festival.id} festival={festival} />

is basically:

FestivalCard({ festival: festival });
And because it’s inside .map():
festivals.map(...)

👉 It means:

“Call FestivalCard once for each item in the array”

👉 You are not manually calling it multiple times
👉 .map() is what causes it to be called multiple times


* * * * * * * * * * * *

🧩 1. Do props values always need {} ?

👉 Rule:
Use {} when the value is JavaScript
Don’t use {} for plain strings

✅ Examples
<MyComp name="Vincent" />        // string → no {}
<MyComp age={25} />             // number → {}
<MyComp isOpen={true} />        // boolean → {}
<MyComp data={festival} />      // object → {}
<MyComp onClick={handleClick} /> // function → {}

👉 So yes—for things like onClick, you MUST use {} because it’s JavaScript (a function).


🧩 2. Destructuring Props

You wrote:

“the name at the top of the function is the prop name right?”

✔ Correct.

function FestivalCard({ festival, onClick })

This means:

props = {
  festival: {...},
  onClick: function
}

And destructuring is:

const festival = props.festival;
const onClick = props.onClick;

🧠 Important understanding:

✔ The name (festival) becomes a local variable
✔ It holds whatever value was passed in

So yes—your statement is right:

“wherever the name is used, what the prop contains is implemented”

Example:
<h5>{festival.name}</h5>
👉 React uses the actual object passed in.


🧩 3. Why wrap setSelectedFestival(festival) in a function?
You said:

“so that it is not called immediately”

✔ EXACTLY RIGHT.

❌ This is WRONG:
onClick={setSelectedFestival(festival)}

👉 This runs immediately when the component renders
(not when clicked ❌)

✅ Correct:
onClick={() => setSelectedFestival(festival)}

👉 Now:
You pass a function

React calls it only when clicked


🧩 4. Is the setter a function?

✔ YES
const [selectedFestival, setSelectedFestival] = useState(null);


selectedFestival → value (state)
setSelectedFestival → function (updates state)


🧩 5. What happens when you click?

When clicked:
setSelectedFestival(festival);

👉 React updates state:
selectedFestival = {  id: 1,  name: "Diwali",  ...}


🧩 6. How do you access the data?
You said:

“we use selectedFestival.name”

✔ PERFECT
Example:
selectedFestival.name
selectedFestival.country
selectedFestival.description

👉 You’re accessing properties of the object stored in state.

🧠 Final Mental Model (Lock this in)
Prop passed → becomes variable via destructuring → used inside component
Click event → calls function → updates state → UI re-renders → new data appears

🔥 One Small Correction (to be precise)
You said:

“added to the selected festival state”

👉 Slight refinement:

It doesn’t “add”
It replaces the state

So:
setSelectedFestival(festival);

means:
“selectedFestival is now this object”

* * * *

🔥 Key Idea

When you click:

setSelectedFestival(festival);

<div className="row mt-5">
        {festivals.map((festival) => (
          <FestivalCard key={festival.id} festival={festival}  onClick={() => setSelectedFestival(festival)} />
        ))}
      </div>

👉 You are saying:

“Take this festival from the loop and store it globally (in state) so other parts of the UI can use it.”


* * * * * *

🔥 What’s really happening

Your modal has classes like:

<div className="modal fade show d-block">

Bootstrap’s .modal uses:

position: fixed;
top: 0;
left: 0;
width: 100%;
height: 100%;

👉 This means:

The modal is removed from normal layout and placed on top of the entire screen

🧠 So even though in your code:
<div className="container">
  ...
  <div className="modal">...</div>
</div>

👉 In reality (browser rendering):

Modal ignores container
→ sticks to viewport (entire screen)
→ overlays everything

🎯 That’s why:
When you added:

.modal {
  background: black;
}

👉 It covered the whole screen

💡 Correct way (overlay effect)

Use transparency:

.modal {
  background: rgba(0, 0, 0, 0.6);
}

👉 This gives:

Dark overlay
Still shows content behind

🧠 Key Difference (Very Important)
position: fixed    → relative to SCREEN (viewport)
position: absolute → relative to PARENT (if positioned)


*  *  *  *  *  *  

🧩 1. What if user selects “All” for both?

You said:

“there is no ‘All’ in the JSON… so what happens?”

👉 Key idea:

“All” is NOT meant to match the data.
It’s a special flag that disables filtering.

Look at one condition:

(selectedReligion === "All Religions" || festival.religion === selectedReligion)

If user selects "All Religions":

selectedReligion === "All Religions" → true

So the whole expression becomes:

true || anything → true

👉 So religion check ALWAYS passes.


Same for month:
selectedMonth === "All Months" → true

👉 Month check ALWAYS passes.

Now combine with &&:
true && true → true

👉 So EVERY festival is included.

✅ Final Answer:

If user selects “All” for both → no filtering happens → all festivals are shown


🧠 Your last statement (almost correct)

You said:

“condition of the and operator is satisfied because selectedReligion and selectedMonth are set to All”

✔ Correct idea, but let’s phrase it properly:

👉 It’s not just because they are “All”

👉 It’s because:

selectedReligion === "All Religions" → makes condition1 true
selectedMonth === "All Months" → makes condition2 true

So:

true && true → true

* * 

🧩 1. Your first statement (important correction)

You said:

“it keeps objects with religion Christian and at the same time keeps any object with month December”

That phrasing can mislead you.

❗ What actually happens:

👉 The filter checks each festival ONE at a time

It does not:

first collect all Christians
then collect all December

✅ Correct understanding:

For each festival, React asks:

Does THIS festival match religion condition?
AND
Does THIS festival match month condition?

Example:

If user selects:

selectedReligion = "Christian"
selectedMonth = "December"

For Christmas:
religion = Christian ✅
month = December ✅
→ INCLUDED


For another festival:
religion = Christian ✅
month = November ❌
→ EXCLUDED

👉 So:

It’s NOT combining separate groups
It’s filtering each object individually


🧩 2. This part—you got it RIGHT ✅

You said:

“All for religion + November for month → only November festivals show”

✔ PERFECT

Let’s break it:

Condition 1 (Religion):
selectedReligion === "All Religions" → true

👉 So:

true || anything → true

✔ No filtering on religion


Condition 2 (Month):
festival.month === "November"

👉 Only November passes


Combine:
true && (month match)

👉 Final result depends ONLY on month

✅ So YES:

Output = only festivals in November


🧠 Final Mental Model (Very Important)
Each filter works independently:

"All" → disables that filter
Specific value → applies that filter

Final result:
All active filters must pass (AND)


🔥 Super Clean Summary

| Selection            | Result                       |
| -------------------- | ---------------------------- |
| All + All            | Show everything              |
| Christian + All      | Only Christian               |
| All + November       | Only November                |
| Christian + December | Only festivals that are BOTH |


🧩 The Code

const religions = ["All Religions", ...new Set(festivals.map(f => f.religion))];

🧠 What it does (in one sentence)

It creates a list of unique religions from your data, plus an "All" option.

🔍 Step-by-step breakdown

✅ 1. festivals.map(f => f.religion)

This extracts only religions:

[
  "Hindu",
  "Christian",
  "Islam",
  "Hindu"
]

👉 Notice duplicates (Hindu appears twice)

✅ 2. new Set(...)
new Set(["Hindu", "Christian", "Islam", "Hindu"])

👉 A Set automatically removes duplicates:

Set = {"Hindu", "Christian", "Islam"}


✅ 3. ... (spread operator)
[..."Hindu", "Christian", "Islam"]

👉 Converts Set back into an array:

["Hindu", "Christian", "Islam"]

✅ 4. Adding "All"
["All", ...uniqueReligions]

Final result:

["All", "Hindu", "Christian", "Islam"]

🧠 Final Meaning

“Give me all unique religions from the data, plus an All option”

⚠️ Common confusion
❌ “Set is like an array”

No.

Array → allows duplicates
Set → unique values only


👍 Summary

map → extract values
Set → remove duplicates
... → convert back to array
+ "All" → default option


🧠 What is Set in JavaScript?
new Set(...)

👉 A Set is a built-in JavaScript object type (yes, it is an object)

BUT it is a special kind of object designed to store:

❗ Only unique values (no duplicates)


🧩 So is it an object?
✔ Yes

typeof new Set()
// "object"

But…

❗ It is NOT a normal object like:
{ name: "Diwali", country: "India" }


🧠 What makes Set different?
1. It stores only values (not key-value pairs)
new Set(["Hindu", "Christian", "Hindu"])

👉 Internally becomes:

Hindu
Christian

Duplicates removed automatically.


2. It is NOT an array

Even though it looks like one, it's different:

| Feature           | Array | Set                 |
| ----------------- | ----- | ------------------- |
| Allows duplicates | ✔     | ❌                   |
| Indexing (arr[0]) | ✔     | ❌                   |
| Order             | ✔     | ✔ (insertion order) |
| Type              | Array | Object (Set type)   |


🔁 Why do we use ... (spread) with Set?

Because:

❗ Set is NOT an array

So you cannot directly do:

set.map(...) ❌


So we convert it:
[...new Set([...])]

👉 This means:

Take Set → spread its values → put into array


🧠 What does spread (...) do here?

It does NOT “convert” Set into array by itself.

👉 It extracts values one by one

Example:

const set = new Set(["Hindu", "Christian"]);

console.log([...set]);

Becomes:

["Hindu", "Christian"]


🧩 So your original line:
const religions = ["All", ...new Set(festivals.map(f => f.religion))];

Breaks down like this:

Step 1:
festivals.map(f => f.religion)
→ ["Hindu", "Christian", "Hindu"]

Step 2:
new Set(...)
→ {"Hindu", "Christian"}

Step 3:
...Set
→ "Hindu", "Christian"

Step 4:
["All", "Hindu", "Christian"]


🧠 Final Mental Model
Array → duplicates allowed
Set → only unique values
Spread (...) → extracts values into a new array


🚨 Important clarification

“does Set convert it to an object?”

✔ Yes technically it is an object
❗ But NOT a normal object you use like {}

It’s a special built-in structure (Set object).


- - - - - - - - - - - - - - - -

THE INCLUDE METHOD AND FILTER EXPLANATION:

🔹 What includes() does
festival.name.toLowerCase().includes(searchTerm.toLowerCase())

👉 This returns:

true → if the name contains the search term
false → if it doesn’t

🔹 How filter() uses that

filter() expects the callback to return true or false:

array.filter(item => condition)
true → keep the item
false → discard the item

🔹 So your combined logic

return (
  (selectedReligion === "All" || festival.religion === selectedReligion) &&
  (selectedMonth === "All" || festival.month === selectedMonth) &&
  festival.name.toLowerCase().includes(searchTerm.toLowerCase())
);

👉 This means:

“Keep this festival ONLY IF:

religion matches (or ‘All’), AND
month matches (or ‘All’), AND
name contains the search term”

”
🔹 Important clarification (this is the key insight)

You said:

“if includes runs true, filter returns that value”

Almost right — but more accurately:

includes() does NOT return the item
It returns a boolean, and filter() uses that boolean to decide whether to include the item


🔹 Step-by-step example

Imagine:

festival.name = "Diwali"
searchTerm = "di"

Then:

"diwali".includes("di") → true

So the whole condition becomes:

true && true && true → true

👉 filter() keeps that festival in the new array


🔹 If it doesn’t match
"diwali".includes("zo") → false

Then:

true && true && false → false

👉 filter() removes it (removes the festival from the new array)

🔑 Final takeaway
includes() → returns true/false
filter() → uses that boolean to keep or remove items

Your logic works perfectly:

“Only include items where the name contains the search term”
*/